common:
  output_directory: .
  chunksize: 1000000

steps:
  - type: remove_duplicates
    parameters:
      inputs: [raw.zh, raw.en]
      outputs: [zh.dedup, en.dedup]

  - type: filter
    parameters:
      inputs: [zh.dedup, en.dedup]
      outputs: [zh.rules, en.rules]
      filterfalse: false
      filters:
        - LengthFilter:
            unit: [char, word]
            min_length: 1
            max_length: 200
        - CharacterScoreFilter:
            scripts: [Han, Latin]
            thresholds: [0.5, 0.8]
        - SimilarityFilter:
            unit: [char, word]
        - RegExpFilter:
            regexps: [".*[\\u4E00-\\u9FA5]+.*", ".*[A-Za-z]+.*"]
            accept_match: true
        - RegExpFilter:
            regexps: [".*[\\u4E00-\\u9FA5]+.*", "[^\\u4E00-\\u9FA5]+$"]
            accept_match: true

  - type: train_alignment
    parameters:
      src_data: zh.rules
      tgt_data: en.rules
      scores: align_score.jsonl
      output: align.priors
      parameters:
        model: 3
        src_tokenizer: [jieba, zh]
        tgt_tokenizer: [moses, en]
