common:
  output_directory: .

steps:

  - type: preprocess
    parameters:
      inputs: [train.zh, train.en]
      outputs: [train.zh.tok, train.en.tok]
      preprocessors:
        - Tokenizer:
            tokenizer: [jieba, moses]
            languages: [zh, en]
          
  - type: preprocess
    parameters:
      inputs: [train.zh.tok.codeswich, train.en.tok.codeswich]
      outputs: [train.zh.codeswich, train.en.codeswich]
      preprocessors:
        - Detokenizer:
            tokenizer: [jieba, moses]
            languages: [zh, en]
