common:
  output_directory: .

steps:
  - type: remove_duplicates
    parameters:
      inputs: [zh, en]
      outputs: [zh.dedup, en.dedup]

  - type: filter
    parameters:
      inputs: [zh.dedup, en.dedup]
      outputs: [zh.rules, en.rules]
      filterfalse: false
      filters:
        - LengthFilter:
            unit: [char, word]
            min_length: 1
            max_length: 200
        - CharacterScoreFilter:
            scripts: [Han, Latin]
            thresholds: [0.5, 0.8]
        - SimilarityFilter:
            unit: char
        - RegExpFilter:
            regexps: [".*[\\u4E00-\\u9FA5]+.*", ".*[A-Za-z]+.*"]
            accept_match: true
        - RegExpFilter:
            regexps: [".*[\\u4E00-\\u9FA5]+.*", "[^\\u4E00-\\u9FA5]+$"]
            accept_match: true

  - type: subset
    parameters:
      inputs: [zh.rules, en.rules]
      outputs: [zh.subset, en.subset]
      size: 3000

  - type: filter
    parameters:
      inputs: [zh.subset, en.subset]
      outputs: [test.zh, test.en]
      filterfalse: false
      filters:
        - LengthFilter:
            min_length: 10
            max_length: 150
            unit: [char, word]
