common:
  output_directory: .

steps:
  - type: remove_duplicates
    parameters:
      inputs: [zh.news]
      outputs: [zh.dedup]

  - type: filter
    parameters:
      inputs: [zh.dedup]
      outputs: [zh.rules]
      filterfalse: false
      n_jobs: 10
      filters:
        - LengthFilter:
            unit: [char]
            min_length: 10
            max_length: 200
        - CharacterScoreFilter:
            scripts: [Han]
            thresholds: [0.8]
        - LanguageIDFilter:
            languages: [zh]
            id_method: fasttext
            thresholds: [0.5]
            fasttext_model_path: lid.176.bin
 

  - type: remove_duplicates
    parameters:
      inputs: [en.news]
      outputs: [en.dedup]


  - type: filter
    parameters:
      inputs: [en.dedup]
      outputs: [en.rules]
      filterfalse: false
      n_jobs: 20
      filters:
        - LengthFilter:
            unit: [word]
            min_length: 10
            max_length: 150
        - CharacterScoreFilter:
            scripts: [Latin]
            thresholds: [0.8]
        - LongWordFilter:
            threshold: 20

        - AlphabetRatioFilter:
            exclude_whitespace: true
            threshold: 0.8

        - LanguageIDFilter:
            languages: [en]
            id_method: fasttext
            thresholds: [0.5]
            fasttext_model_path: lid.176.bin
